apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-bank-api-deployment
  labels:
    app: simple-bank-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: simple-bank-api
  template:
    metadata:
      labels:
        app: simple-bank-api
    spec:
      containers:
        - name: simple-bank-api
          image: 571373535018.dkr.ecr.eu-west-2.amazonaws.com/simplebank:5d34b77b5c5059e1b8e9236d3d7d4960113febba
          imagePullPolicy: Always
          ports:
            - containerPort: 8080